os: linux
dist: xenial
language: python


jobs:
  fast_finish: true
  include:
    - python: 3.6  # Minimum
      env:
        - JOB: 'UNITTEST'
        - FULL_DEPS: true
    - python: 3.8
      env:
        - JOB: 'UNITTEST'
        - FULL_DEPS: true
    - python: 3.8
      env:
        - JOB: 'DOCS'
        - FULL_DEPS: true
        - ENCRYPTION_LABEL: 4b42558754ed
    - python: 3.8
      env:
        - JOB: 'LINT'
        - FULL_DEPS: false
addons:
  apt:
    packages:
      - libblas-dev
      - gfortran
      - ccache

cache:
  pip : true
  directories:
    - $HOME/.ccache

notifications:
  email: false

install:
  - |
    if [[ "$FULL_DEPS" == "true" ]]; then
      pip install --upgrade numpy
      pip install --install-option="--no-cython-compile" "Cython>=0.29"
      pip install -v -e .
    fi
  - |
    if [[ "$JOB" == "UNITTEST" ]]; then
      pip install pytest-cov coveralls
      pip install --upgrade pytest>=3.0.3
    elif [[ "$JOB" == "DOCS" ]]; then
      pip install sphinx sphinx_rtd_theme;
    elif [[ "$JOB" == "LINT" ]]; then
      pip install flake8
    fi
  - pip list

script:
  - |
    if [[ "$JOB" == "UNITTEST" ]]; then
      make test
    elif [[ "$JOB" == "DOCS" ]]; then
      pushd doc
      SPHINXOPTS=-W
      make html && popd
    elif [[ "$JOB" == "LINT" ]]; then
      make lint
    fi

after_success:
  - |
    if [[ "$JOB" == "UNITTEST" ]]; then
      coveralls --rcfile=.coveragerc
    elif [[ "$JOB" == "DOCS" ]]; then
      ./tools/deploy_documentation.sh
    fi
